### ISSUE TITLE
Update to recent version with support for Elasticsearch 7.0

### ISSUE THREAD

**Issue by dschulten** [anjia0532/docker-curator#1]
First of all, thank you for this useful docker image!

Please update to the most recent curator version (currently still on master, release to pypi should come soon) with support for ES 7. 

Maybe also push a version for 5.6.0.

Also may I suggest that you push your image into docker hub with version tags so that one can recognize which curator is baked into which published image.

**Comment by anjia0532** [comment]
1. 5.5.6 releases for 2018.11.14 , es7 is 2019.4.19 
2. modify readme.md curator's version to x.y.z
3. Dockerfile use build arg now, and push to docker hub(https://hub.docker.com/r/anjia0532/docker-curator/tags)
