### ISSUE TITLE
Change System Time Zone

### ISSUE THREAD

**Issue by Patrick-kuo** [anjia0532/docker-curator#2]
Hi there, I was wondering how can I change the container's Time Zone to UTC +8?

**Comment by anjia0532** [comment]
easy to change to UTC+8(like ShangHai timezone) 
fork and change Dockerfile and rebuild image
```bash
FROM python:3.6-alpine

ARG CURATOR_VERSION

RUN \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk update && \
    apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" >  /etc/timezone && \
    rm -rf /var/cache/apk/*

RUN pip install  elasticsearch-curator==${CURATOR_VERSION} &&\
    rm -rf /var/cache/apk/*

COPY ./config/ /config

RUN /usr/bin/crontab /config/crontab.txt

CMD ["/usr/sbin/crond","-f"]
```
but es is use UTC timezone, 
e.g. u create linux task every day at UTC+8 00:00:00 AM(mean's UTC 16:00:00 pm yestoday)
like this
```
0 0 * * * curator --config /config/config_file.yml /config/action_file.yml
```

es index's time is UTC 16:00:00 pm yestoday , if u want to delete or create yestoday index(but in curator,look like today)?

用中文描述下吧，我英文很烂。
es使用的是格林尼治时间，也就是UTC时间。而如果你把curator时区改成东八区，你设置的东八区的凌晨零点去创建或者删除index，很可能操作的不是你想象中的index，这点你需要考虑清楚。

如果执意要改的话，你可以fork我的项目，并且修改Dockerfile，或者也可以pull&run&exec 进去后，手动安装tzdata。

**Comment by Patrick-kuo** [comment]
Hi anjia0532, 能在社群看到中文真是有點興奮，好說正事

1. 請問如果我不修改時間，理論上我系統的時間目前是2019-08-16 06:18:00然後我的Cron時間設置6 20 * * *，應該可以在6:20分的時候觸發這個job才對。但發現沒任何es index被刪除。這樣設置對嗎? (截圖為6:24分的時候)
![Imgur](https://i.imgur.com/pP4s3Dr.png)

2. 請問有什麼辦法可以查看curator是否運行或是觸發了? 有log之類的嗎? 我使用docker logs containerId 查不到任何log紀錄。

**Comment by anjia0532** [comment]
参见 官方日志  https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html#logfile

另外你也可以 `curator --config /path/to/config_file.yml /path/to/action.yml` 手动执行

你的描述和你的写法是有问题的,你的例子是没天晚上20:06执行，而不是你想的上午6:20执行。
```
例子：
# 每月的最后1天
0 0 L * * *

说明：
Linux
*    *    *    *    *    *
-    -    -    -    -    -
|    |    |    |    |    |
|    |    |    |    |    + year [optional]
|    |    |    |    +----- day of week (0 - 7) (Sunday=0 or 7)
|    |    |    +---------- month (1 - 12)
|    |    +--------------- day of month (1 - 31)
|    +-------------------- hour (0 - 23)
+------------------------- min (0 - 59)
```

参考国人的在线crontab工具 https://tool.lu/crontab/

主要需要结合你的日志内容和config.yml和action.yml来看，比如，你的pattern是否正确。

**Comment by Patrick-kuo** [comment]
Hi anjia0532,

終於試出來，但是我必須把所有的Environment 變數都拿掉，ex: ${UNIT_COUNT}。不然會出現以下錯誤:

`
curator.exceptions.ConfigurationError: Configuration: filters: Location: Action ID "1", action "delete_indices", "filters": Bad Value: "None", Configuration: filter: Location: Action ID "1", action "delete_indices", filter #1: {'filtertype': 'age', 'source': 'name', 'direction': 'older', 'timestring': '%Y.%m.%d', 'unit': 'days', 'unit_count': '${UNIT_COUNT}'}: Bad Value: "${UNIT_COUNT}", expected int for dictionary value @ data['unit_count']. Check configuration file.. Check configuration file.
`

都拿掉以後就成功delete index了。

在請問一個問題: 
1. crontab的設定貌似寫死0點0分，是否有方法可以透過docker-compose傳入要設定的檔案時間

**Comment by anjia0532** [comment]
内容写在crontab.txt里，你只要把这个文件替换就行了 。
